apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-prom-histo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-prom-histo
  template:
    metadata:
      labels:
        app: py-prom-histo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"
    spec:
      containers:
      - name: py-prom-histo
        image: synfinmelab/py-prom-histo:v0.5
        imagePullPolicy: IfNotPresent
        command:
        - /opt/scripts/py-prom-histo.py
        env:
        - name: METRIC_NAME_SUFFIX
          value: ''
